/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Uliszs.3d (https://sketchfab.com/uliszs.3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/zeldas-moon-79b426f98d96419b9c7974ca284995d5
Title: zelda's moon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/zeldas_moon.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.M_ROCA__FINAL}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.M_ROCA__FINAL}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/zeldas_moon.glb')

