/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/starShape.glb')
return (
    <group {...props} dispose={null}>
        <mesh
            castShadow
            receiveShadow
            geometry={nodes.Icosphere.geometry}
            scale={2.366}
            material-color="yellow"
        >
            <meshBasicMaterial color="yellow" side={THREE.DoubleSide} />
        </mesh>
    </group>
)
}

useGLTF.preload('/starShape.glb')